---
title: "Isotope cements"
output: html_document
date: "2023-04-04"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Data Import

```{r}
iso_orig <- readxl::read_xlsx("r_Jacquet_carb_with_cements.xlsx")
iso_nz <- readxl::read_xlsx("nelsonsmithisotopes.xlsx")
iso_betts <- readxl::read_xlsx("betts_2018.xlsx", sheet = 8, skip = 1, col_names = TRUE) %>%
  subset(select = 2:4) %>%
  rename("Sample" = "Meters along Section/Core", "d13C" = "d13C ‰VPDB", "d18O" = "d18O‰VPDB")
```

##Data Wrangle

```{r combo}
iso_combo <- iso_orig %>% #combine data with selected values from Nelson and Smith 1996
  select(Cement, d13C, d18O) %>%
  rbind(iso_nz)%>%
  mutate(d13C = d13C/1.95, d18O = d18O/-2.20) #normalize to VPDB that Marissa used
```

```{r combo condensed}
iso_cond <- iso_orig %>% # simplify data by combining into broad categories
  select(Cement, d13C, d18O) %>%
  mutate(Cement = case_when(
    str_detect(Cement, "Microspar") == TRUE ~ "Spar",
    str_detect(Cement, "Micrite") == TRUE ~ "Micrite",
    str_detect(Cement, "Microbial") == TRUE ~ "Microbial",
    TRUE ~ as.character(Cement)
  )) %>%
  rbind(iso_nz) %>%
  mutate(Cement = case_when(
    str_detect(Cement, "NZ Spar") == TRUE ~ "NZ Spar",
    str_detect(Cement, "Fossil") == TRUE ~ "NZ Fossil",
    str_detect(Cement, "Calcite") == TRUE ~ "NZ Calcite Concretion",
    TRUE ~ as.character(Cement)
  ))%>%
  mutate(d13C = d13C/1.95, d18O = d18O/-2.20) #normalize to VPDB that Marissa used
```

```{r orig horizon and bg}
iso_bg <- iso_orig %>% #separates data by red horizon samples and samples above/below
  mutate(Position = case_when(
    str_detect(ID, "1.3m") == TRUE ~ "Non-Horizon",
    str_detect(ID, "AB") == TRUE ~ "Non-Horizon",
    str_detect(ID, "FUWM 4") == TRUE ~ "Non-Horizon",
    TRUE ~ "Horizon"
  ))
```


## Data Ordering

```{r orig ordering}
iso_orig$Cement <- factor(iso_orig$Cement, levels = c("Spar", "Microspar", "Manganese", "Micrite", "Micrite (SSF)", "Micrite (spicule)", "Microbial", "Microbial (SSF)", "Laminar Microbial", "Laminar Microbial (Strom)", "Laminar Microbial (sponge)", "Laminar Calcrete"))
```

```{r combo ordering}
iso_combo$Cement <- factor(iso_combo$Cement, levels = rev(c("Spar", "Microspar", "Manganese", "Micrite", "Micrite (SSF)", "Micrite (spicule)", "Microbial", "Microbial (SSF)", "Laminar Microbial", "Laminar Microbial (Strom)", "Laminar Microbial (sponge)", "Laminar Calcrete", "NZ Spar 1", "NZ Spar 2", "NZ Fossil 1", "NZ Fossil 2", "NZ Fossil 3", "NZ Calcite Concretion 1", "NZ Calcite Concretion 2", "NZ Bulk Skeletal", "NZ Bulk Micrite", "NZ Bulk Dolomicrite")))
```

```{r cond ordering}
iso_cond$Cement <- factor(iso_cond$Cement, levels = c("Spar", "Manganese", "Micrite",  "Microbial", "Laminar Calcrete", "NZ Spar", "NZ Calcite Concretion", "NZ Bulk Micrite", "NZ Bulk Dolomicrite", "NZ Fossil", "NZ Bulk Skeletal"))
```

## Plots

```{r carbon}
carbon <- iso_orig %>% #FU carbon isotopes box
  ggplot(aes(x = d13C, y = Cement)) +
  geom_boxplot() +
  geom_point(aes(color = "red")) +
  geom_vline(xintercept = 0) +
  theme(
    legend.position = "none"
  )
carbon
```

```{r oxygen} 
oxygen <- iso_orig %>% #FU oxygen isotopes box
  ggplot(aes(x = d18O, y = Cement)) +
  geom_boxplot() +
  geom_point(aes(color = "red")) +
  geom_vline(xintercept = 0) +
  theme(
    legend.position = "none"
  )
oxygen
```

```{r both}
carbox <- iso_orig %>% #FU carbon over oxygen scatter
  ggplot(aes(x = d18O, y = d13C, color = Cement)) +
  geom_point() +
  scale_color_brewer(palette = "Paired") +
  #geom_smooth(method = "lm") + #regression lines
  theme(
    panel.background = element_rect(fill = "black", color = "black"),
    legend.key = element_rect(fill ="black"),
  )
carbox
```

```{r carbon w/NZ}
NZcarbon <- iso_combo %>% #FU and NZ carbon box
  ggplot(aes(x = d13C, y = Cement)) +
  geom_boxplot() +
  geom_point(aes(color = "red")) +
  geom_vline(xintercept = 0) +
  theme(
    legend.position = "none",
    panel.grid.major = element_line(color = "black")
  )
NZcarbon
```

```{r oxygen w/NZ}
NZoxygen <- iso_combo %>% #FU and NZ oxygen box
  ggplot(aes(x = d18O, y = Cement)) +
  geom_boxplot() +
  geom_point(aes(color = "red")) +
  geom_vline(xintercept = 0) +
  theme(
    legend.position = "none",
    panel.grid.major = element_line(color = "black")
  )
NZoxygen
```

```{r both w/NZ}
bigcolor <- c("#E0933B", "#D4635B", "#FF3C3C", "#8C0800", "#6F00B0", "#7CB000", "#3F8325", "#00BF32", "#5E63DD", "#0002CF", "#987A21", "#BE6000", "#5DEFE8", "#00FFF3", "#48FF7C", "#7CFF48", "#FFFB48", "#FFC948", "#A048FF", "#D248FF", "#FF48ED", "#FF4873")

NZcarbox <- iso_combo %>% #FU and NZ carbon over oxygen scatter
  ggplot(aes(x = d18O, y = d13C, color = Cement)) +
  geom_point() +
  scale_color_manual(values = bigcolor) +
  #geom_smooth(method = "lm") + #regression lines
  theme(
    panel.background = element_rect(fill = "black", color = "black"),
    legend.key = element_rect(fill ="black"),
  )
NZcarbox
```

```{r both w/NZ condensed}
smallcolor <- c("#1B43AA", "#995AB1", "#4A9252", "#CB4E4E", "#E0933B", "#009AE4", "#16FFD1", "#ACD600", "#00F81B", "#F80000", "#FF4C16")

NZcond <- iso_cond %>% #FU and NZ simplified category carbon over oxygen scatter
    ggplot(aes(x = d18O, y = d13C, color = Cement)) +
  geom_point() +
  scale_color_manual(values = smallcolor) +
  #geom_smooth(method = "lm") + #regression lines
  theme(
    panel.background = element_rect(fill = "black", color = "black"),
    legend.key = element_rect(fill ="black"),
  )
NZcond
```

```{r carbon bg}
carbon_bg <- iso_bg %>% #FU horizon/bg carbon box
  ggplot(aes(x = d13C, y = Cement)) +
  geom_boxplot() +
  geom_jitter(aes(color = Pos), width = 0, height=.1) +
  geom_vline(xintercept = 0) +
  theme(
   # legend.position = "none"
  )
carbon_bg
```

```{r oxygen bg}
oxygen_bg <- iso_bg %>% #FU horizon/bg carbon box
  ggplot(aes(x = d18O, y = Cement)) +
  geom_boxplot() +
  geom_jitter(aes(color = Pos), width = 0, height=.1) +
  geom_vline(xintercept = 0) +
  theme(
   # legend.position = "none"
  ) +
  ylab("Texture")
oxygen_bg
```

```{r simplified carbon}
iso_bg %>%
  mutate(Cement = case_when(
    str_detect(Cement, "Microspar") == TRUE ~ "Spar",
    str_detect(Cement, "Micrite") == TRUE ~ "Micrite",
    str_detect(Cement, "Microbial") == TRUE ~ "Microbial",
    TRUE ~ as.character(Cement)
  ))%>%
  ggplot(aes(x = d13C, y = Cement)) +
  geom_boxplot() +
  geom_jitter(aes(color = Position), width = 0, height=.1) +
  geom_vline(xintercept = 0) +
  ylab("Texture") +
  xlab("δ13C") 
```

```{r simplified oxygen}
iso_bg %>%
  mutate(Cement = case_when(
    str_detect(Cement, "Microspar") == TRUE ~ "Spar",
    str_detect(Cement, "Micrite") == TRUE ~ "Micrite",
    str_detect(Cement, "Microbial") == TRUE ~ "Microbial",
    TRUE ~ as.character(Cement)
  ))%>%
  ggplot(aes(x = d18O, y = Cement)) +
  geom_boxplot() +
  geom_jitter(aes(color = Position), width = 0, height=.1) +
  geom_vline(xintercept = 0) +
  ylab("Texture")
  xlab("δ18O")
```

```{r both convex hull}
hull <- iso_orig %>% #FU simplified carbon over oxygen with convex hull
  group_by(Cement) %>%
  select(Cement, d13C, d18O) %>%
#  mutate(d13C = d13C/1.95, d18O = d18O/-2.20) %>% #normalize to VPDB that Marissa used
  mutate(Cement = case_when( #comment out mutate sections for full data
    str_detect(Cement, "Microspar") == TRUE ~ "Spar",
    str_detect(Cement, "Micrite") == TRUE ~ "Micrite",
    str_detect(Cement, "Microbial") == TRUE ~ "Microbial",
    TRUE ~ as.character(Cement)
  )) %>%
  slice(chull(d18O, d13C))

carbox <- iso_orig %>%
  select(Cement, d13C, d18O) %>%
  mutate(Cement = case_when( #comment out mutate sections for full data
    str_detect(Cement, "Microspar") == TRUE ~ "Spar",
    str_detect(Cement, "Micrite") == TRUE ~ "Micrite",
    str_detect(Cement, "Microbial") == TRUE ~ "Microbial",
    TRUE ~ as.character(Cement)
  ))%>%
#  mutate(d13C = d13C/1.95, d18O = d18O/-2.20) %>% #normalize to VPDB that Marissa used 
  ggplot(aes(x = d18O, y = d13C, color = Cement)) +
  geom_point() +
  #scale_color_brewer(palette = "Paired") +
  geom_polygon(data = hull, alpha = .25, aes(fill = Cement)) +
  #geom_smooth(method = "lm") + #regression lines
  theme(
    panel.background = element_rect(fill = "black", color = "black"),
    legend.key = element_rect(fill ="black")
  ) +
  xlab("δ18O") +
  ylab("δ13C") +
  scale_fill_discrete(name = "Texture") +
  scale_color_discrete(name = "Texture")
carbox
```

```{r betts plot}
whoops <- iso_bg %>%
  mutate(Sample = case_when(
    str_detect(ID, "AB") == TRUE ~ "752.1",
    str_detect(ID, "1.3m") == TRUE ~ "753.3",
    str_detect(ID, "1.5m") == TRUE ~ "750.5",
    str_detect(ID, "3m") == TRUE ~ "749",
    TRUE ~ "752"))

ggplot() + 
  geom_point(data = iso_betts, aes(x = d18O, y = Sample)) +
  geom_point(data = whoops, aes(x = d18O, y = Sample), color = "red") +
  geom_point(data = iso_betts, aes(x = d13C, y = Sample), color = "blue") +
  geom_point(data = whoops, aes(x = d13C, y = Sample), color = "orange")

```