---
title: "iso stats"
author: "Clara Wong"
date: "2023-05-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(PMCMRplus)
library(pracma)
```

## Data Import
Datasheet
```{r data}
iso_orig <- readxl::read_xlsx("r_Jacquet_carb_with_cements.xlsx")
iso_combo <- iso_orig %>% #simplifies cements
  mutate(Cement = case_when(
    str_detect(Cement, "Microspar") == TRUE ~ "Spar",
    str_detect(Cement, "Micrite") == TRUE ~ "Micrite",
    str_detect(Cement, "Microbial") == TRUE ~ "Microbial",
    TRUE ~ as.character(Cement)
   ))
```

## Plot
```{r density}
dense <- ggplot(iso_orig, aes(x = d18O, y = d13C)) +
  stat_density2d(aes(fill = after_stat(level)), geom = "polygon", color = "white") +
  scale_fill_continuous(type = "viridis")

contours <- layer_data(dense)

centroid1 <- contours %>%
  filter(piece == 16)
centroid1 <- poly_center(centroid1$x, centroid1$y)
centroid2 <- contours %>%
  filter(piece == 3)
centroid2 <- poly_center(centroid2$x, centroid2$y)
centroid3 <- contours %>%
  filter(piece == 6)
centroid3 <- poly_center(centroid3$x, centroid3$y)

dense + 
  geom_point(aes(x = centroid1[1], y = centroid1[2]), color = "red") +
  geom_point(aes(x = centroid2[1], y = centroid2[2]), color = "red") +
  geom_point(aes(x = centroid3[1], y = centroid3[2]), color = "red") 
```

## Normality
```{r kolmogorov-smirnov}
ks_result <- iso_combo %>%
  group_by(Cement) %>%
  summarize(
    ks_C <- ks.test(d13C, "pnorm")$p.value,
    ks_O <- ks.test(d18O, "pnorm")$p.value
  )
colnames(ks_result) <- c("Cement", "d13C_p", "d18O_p")
ks_result
```

```{r shapiro-wilk}
sw_result <- iso_combo %>%
  group_by(Cement) %>%
  filter(Cement != "Manganese") %>%
  summarize(
    sw_C <- shapiro.test(d13C)$p.value,
    sw_O <- shapiro.test(d18O)$p.value
  )
colnames(sw_result) <- c("Cement", "d13C_p", "d18O_p")
sw_result
```


## Kruskal-Wallis
```{r kruskal-wallis 13C}
kw_result <- kruskal.test(x = iso_combo$d13C, g = iso_combo$Cement)
kw_result
```
```{r kruskal-wallis 18O}
kw_result <- kruskal.test(x = iso_combo$d18O, g = iso_combo$Cement)
kw_result
```

#Nemenyi
```{r nemenyi 13C}
nemenyi_result <-
kwAllPairsNemenyiTest(d13C ~ as.factor(Cement), data = iso_combo)
nemenyi_result
```
```{r nemenyi 18O}
nemenyi_result <-
kwAllPairsNemenyiTest(d18O ~ as.factor(Cement), data = iso_combo)
nemenyi_result
```